### ISSUE TITLE
Bubble Sort Review

### ISSUE THREAD

**Issue by shpakkdv** [kgalushchak/evo-ts-bootcamp#1]
1. No, no, no... [here](https://github.com/kgalushchak/evo-ts-bootcamp/blob/master/01-bubble-sort/src/App.tsx#L13) `Component<Record<string, never>, AppState>` ->
```ts
Component<void, AppState>
```
or
```ts
Component<{}, AppState>
```
or
```tsx
interface AppProps {}

class App extends Component<AppProps, AppState> {}
```

2. Or you can use arrow functions in methods instead of [this](https://github.com/kgalushchak/evo-ts-bootcamp/blob/master/01-bubble-sort/src/App.tsx#L21-L22):
```ts
newArrayBtnHandler = () => {}
```

3. Don't need to do [it](https://github.com/kgalushchak/evo-ts-bootcamp/blob/master/01-bubble-sort/src/App.tsx#L29-L30) several times in a row:
```ts
this.setState({
  status: Status.notStarted,
  array: getRandomNumbersArray(),
});
```

4.   `NodeJS.Timeout` is an incorrect type [here](https://github.com/kgalushchak/evo-ts-bootcamp/blob/master/01-bubble-sort/src/App.tsx#L25). Try `window.setInterval` explicitly.

5. Don't use `!` (like [here](https://github.com/kgalushchak/evo-ts-bootcamp/blob/master/01-bubble-sort/src/App.tsx#L42)). The types should be correct! Try `window.clearInterval` explicitly.

6. These components can be Function (Stateless) Component: [ArrayItem](https://github.com/kgalushchak/evo-ts-bootcamp/blob/master/01-bubble-sort/src/components/ArrayItem.tsx#L7) and [ControlButton](https://github.com/kgalushchak/evo-ts-bootcamp/blob/master/01-bubble-sort/src/components/ControlButton.tsx#L8)

7. All styles should be in css files: [here](https://github.com/kgalushchak/evo-ts-bootcamp/blob/master/01-bubble-sort/src/components/ControlButton.tsx#L10-L17), [here (except height)](https://github.com/kgalushchak/evo-ts-bootcamp/blob/master/01-bubble-sort/src/components/ArrayItem.tsx#L9-L17), [here](https://github.com/kgalushchak/evo-ts-bootcamp/blob/master/01-bubble-sort/src/components/Array.tsx#L10-L13), etc.

There are bugs in the app. You can click `Start` multiple times and the speed will be changed. Also, if after several clicks on `Start`, you click `New array`, sorting will be run and the app's status will be incorrect.
There is a lack of `Pause` functionality 🙂

**Comment by kgalushchak** [comment]
@shpakkdv thank you for the review! All comments (except point 6) and the bug are fixed.
